### ISSUE TITLE
Static Meteo Files

### ISSUE THREAD

**Issue by delcacho** [fmidev/silam-model#4]
Hello,

I am trying to run the tst_pollen control file.

Where can I find the following files?

static_meteo_file = GRIB e:\data\meteo\ec_land_use_global.sfc
   static_meteo_file = GRADS d:\model\silam_v5_7\ini\tz_index_02deg.grads.super_ctl
   static_meteo_file = GRIB d:\meteo\EC_vegfrac_glob_2012.sfc    #/lustre/tmp/silamdata/tmp/ecglob100_VEG__latest.sfc
   static_meteo_file = GRIB d:\meteo\EC_orography_2012.fixed 
   static_meteo_file = GRADS d:\data\emis\sea_salt\salinity_map_global_1deg.fld_water_salinity.grads.super_ctl
   static_meteo_file = GRADS d:\meteo\lai.super_ctl

**Comment by rkouznetsov** [comment]
Thank you for your interest to the Silam model. Some of the files seem to be not actually needed for pollen simulations, others have been outdated.

I hope you have compiled Silam and managed with the toypoint case.  Please contact us by e-mail describing the problem you try to address and your  desired setup. Then we could elaborate something for you.
